# Generated by Django 4.2.7 on 2025-07-28 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('styles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('generation', 'Image Generation'), ('edit', 'Image Editing'), ('style_transfer', 'Style Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('moderating', 'Content Moderation'), ('processing', 'Processing with OpenAI'), ('streaming', 'Streaming Response'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('prompt', models.TextField()),
                ('openai_parameters', models.JSONField(default=dict)),
                ('openai_request_id', models.CharField(blank=True, max_length=255)),
                ('openai_response', models.JSONField(blank=True, default=dict)),
                ('moderation_passed', models.BooleanField(default=False)),
                ('moderation_details', models.JSONField(blank=True, default=dict)),
                ('moderation_checked_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='images.image')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='styles.style')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processing Job',
                'verbose_name_plural': 'Processing Jobs',
                'db_table': 'processing_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProcessingQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_generations', models.PositiveIntegerField(default=0)),
                ('daily_edits', models.PositiveIntegerField(default=0)),
                ('daily_style_transfers', models.PositiveIntegerField(default=0)),
                ('last_reset_date', models.DateField(auto_now_add=True)),
                ('total_generations', models.PositiveIntegerField(default=0)),
                ('total_edits', models.PositiveIntegerField(default=0)),
                ('total_style_transfers', models.PositiveIntegerField(default=0)),
                ('monthly_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Processing Quota',
                'verbose_name_plural': 'User Processing Quotas',
                'db_table': 'user_processing_quotas',
            },
        ),
        migrations.CreateModel(
            name='StreamingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('partial_image', 'Partial Image'), ('completed', 'Completed'), ('error', 'Error')], max_length=20)),
                ('partial_image_index', models.PositiveIntegerField(blank=True, null=True)),
                ('b64_data', models.TextField(blank=True)),
                ('event_metadata', models.JSONField(default=dict)),
                ('openai_created_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaming_events', to='processing.processingjob')),
            ],
            options={
                'verbose_name': 'Streaming Event',
                'verbose_name_plural': 'Streaming Events',
                'db_table': 'streaming_events',
                'ordering': ['received_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('job_type', models.CharField(choices=[('generation', 'Image Generation'), ('edit', 'Image Editing'), ('style_transfer', 'Style Transfer')], max_length=20)),
                ('default_parameters', models.JSONField(default=dict)),
                ('prompt_template', models.TextField()),
                ('preview_image', models.URLField(blank=True, max_length=500)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('is_public', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processing Template',
                'verbose_name_plural': 'Processing Templates',
                'db_table': 'processing_templates',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_b64', models.TextField()),
                ('result_format', models.CharField(max_length=10)),
                ('result_size', models.CharField(max_length=20)),
                ('result_quality', models.CharField(max_length=10)),
                ('result_background', models.CharField(max_length=15)),
                ('s3_key', models.CharField(blank=True, max_length=500)),
                ('s3_url', models.URLField(blank=True, max_length=1000)),
                ('openai_created_at', models.DateTimeField(blank=True, null=True)),
                ('token_usage', models.JSONField(blank=True, default=dict)),
                ('user_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='processing.processingjob')),
            ],
            options={
                'verbose_name': 'Processing Result',
                'verbose_name_plural': 'Processing Results',
                'db_table': 'processing_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
