# Generated by Django 4.2.7 on 2025-08-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for async processing', max_length=255),
        ),
    ]
