# Generated by Django 4.2.7 on 2025-08-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_processingjob_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether results from this job are publicly visible'),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
