# Generated by Django 4.2.7 on 2025-08-11 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processing', '0003_processingjob_is_public_processingresult_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingResultLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='processing.processingresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_result_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processing Result Like',
                'verbose_name_plural': 'Processing Result Likes',
                'db_table': 'processing_result_likes',
                'indexes': [models.Index(fields=['result'], name='processing__result__5bde97_idx'), models.Index(fields=['user'], name='processing__user_id_150e5f_idx')],
                'unique_together': {('user', 'result')},
            },
        ),
    ]
