# Generated by Django 4.2.7 on 2025-08-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_processingresultlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
